theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
auto-format = true

[editor.cursor-shape]
normal = "block"
select = "underline"

[keys.normal]
esc = ['collapse_selection', 'keep_primary_selection']

[editor.file-picker]
hidden = false
